### ISSUE TITLE
/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/network.py", line 900, in _run_internal_graph     tensor = tensor_dict[str(id(x))].pop() IndexError: pop from empty list

### ISSUE THREAD

**Issue by upadhyatejas** [aryanmisra/NeuraScale#2]

**Comment by deepentropy** [comment]
Got the same issue. While running:

`python srgan.py -p mj-dance.png`

I get:
```
2020-07-10 09:46:38.367654: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-07-10 09:46:39.371361: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-07-10 09:46:39.371392: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: UNKNOWN ERROR (-1)
2020-07-10 09:46:39.371412: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2020-07-10 09:46:39.371584: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-10 09:46:39.395681: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3792880000 Hz
2020-07-10 09:46:39.396564: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x52e8d70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-10 09:46:39.396587: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg19/vgg19_weights_tf_dim_ordering_tf_kernels_notop.h5
80142336/80134624 [==============================] - 1s 0us/step
Traceback (most recent call last):
  File "srgan.py", line 344, in <module>
    gan = SRGAN()
  File "srgan.py", line 40, in __init__
    self.vgg = self.build_vgg()
  File "srgan.py", line 101, in build_vgg
    img_features = vgg(img)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 386, in call
    inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 518, in _run_internal_graph
    output_tensors.append(tensor_dict[x_id].pop())
IndexError: pop from empty list

```

**Comment by deepentropy** [comment]
Installing the right version of Tensorflow fixed the issue.
TF version: 2.0.0
