### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by mclean-connor** [aryanmisra/NeuraScale#3]
KerasTensor(type_spec=TensorSpec(shape=(None, 400, 400, 3), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'")
Traceback (most recent call last):
  File "main/srgan.py", line 345, in <module>
    gan = SRGAN()
  File "main/srgan.py", line 40, in __init__
    self.vgg = self.build_vgg()
  File "main/srgan.py", line 102, in build_vgg
    img_features = vgg(img)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 424, in call
    return self._run_internal_graph(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 570, in _run_internal_graph
    output_tensors.append(tensor_dict[x_id].pop())
IndexError: pop from empty list

**Comment by boriswinner** [comment]
Did you manage to find a solution?
